name: Build (master)

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - uses: actions/cache@v2
      id: target-cache
      with:
        path: ./target/*
        key: ${{ github.sha }}

  build_and_publish_docker_image:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        id: target-cache
        with:
          path: ./target/*
          key: ${{ github.sha }}
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Get Project Version from POM
        id: project-version
        uses: CptMokoena/maven-get-version-action@1.0.3
      - name: Build and Push (latest)
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./src/main/resources/Dockerfile
          build-args: |
            JAR_FILE=self-information-${{ steps.project-version.outputs.version }}.jar
          push: true
          tags: stefan-ka/ost-self-information-app:latest
      - name: Build and Push (latest)
        if: github.event_name == 'release'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./src/main/resources/Dockerfile
          build-args: |
            JAR_FILE=self-information-${{ steps.project-version.outputs.version }}.jar
          push: true
          tags: stefan-ka/ost-self-information-app:${{ github.event.release.tag_name }}